### ISSUE TITLE
Add flag to enable/disable command suggestions in notifications

### ISSUE THREAD

**Issue by patcon** [hubot-archive/hubot-pagerduty-github#1]
Add back in some version of what was removed here: 72912c0

**Comment by chrisgagne** [comment]
I've posted a $25 bounty for this on behalf of PagerDuty over at BountySource.com: https://www.bountysource.com/issues/1824431-add-flag-to-enable-disable-command-suggestions-in-notifications

**Comment by patcon** [comment]
Hey man, I think this is the more active package, and it's maintained by github themselves :)
https://github.com/hubot-scripts/hubot-pager-me

**Comment by technicalpickles** [comment]
cc https://github.com/hubot-scripts/hubot-pagerduty-github/issues/2 for deprecating
